spring.application.name=submission

RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
KAFKA_BOOTSTRAP_SERVERS=localhost:9092
REDIS_HOST=localhost
REDIS_PORT=6379

spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.delivery.timeout.ms=10000
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.properties.allow.auto.create.topics=true